# Generated by Django 2.2 on 2021-04-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
