# Generated by Django 2.2 on 2021-04-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations_app', '0003_usermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
