# Generated by Django 2.2 on 2021-04-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations_app', '0008_auto_20210411_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
