# Generated by Django 2.2 on 2021-04-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations_app', '0018_auto_20210412_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='pic',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
