# Generated by Django 2.2 on 2021-04-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creations_app', '0019_auto_20210413_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_banner', models.ImageField(upload_to='static/images/')),
                ('instagram', models.CharField(default=None, max_length=70)),
                ('facebook', models.CharField(default=None, max_length=70)),
                ('youtube', models.CharField(default=None, max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('my_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_obj', to='creations_app.User')),
            ],
        ),
    ]
